# Generated by Django 2.2.4 on 2019-09-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=10)),
                ('anonymity', models.CharField(max_length=10)),
                ('net_type', models.CharField(max_length=10)),
                ('ip_location', models.CharField(max_length=100)),
                ('verify_time', models.DateTimeField()),
                ('priority', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'ip_proxy',
                'ordering': ['-verify_time'],
                'unique_together': {('ip', 'port')},
            },
        ),
    ]
