# Generated by Django 2.2.4 on 2019-08-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpProxy',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('port', models.CharField(max_length=10)),
                ('anonymity', models.CharField(blank=True, max_length=10, null=True)),
                ('net_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_location', models.CharField(max_length=100)),
                ('verify_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ip_proxy',
                'unique_together': {('ip', 'port')},
            },
        ),
    ]
