# Generated by Django 2.2.4 on 2019-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipproxy',
            name='verify_time_0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ipproxy',
            name='verify_time',
            field=models.DateTimeField(),
        ),
    ]
