# Generated by Django 2.2.4 on 2019-08-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_proxy', '0002_auto_20190826_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipproxy',
            name='verify_time_0',
        ),
    ]
