# Generated by Django 2.2.10 on 2020-04-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_proxy', '0002_ipproxy_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipproxy',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
