# Generated by Django 2.2.4 on 2019-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_proxy', '0003_remove_ipproxy_verify_time_0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipproxy',
            options={'ordering': ['-verify_time']},
        ),
        migrations.AlterField(
            model_name='ipproxy',
            name='anonymity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ipproxy',
            name='net_type',
            field=models.CharField(max_length=10),
        ),
    ]
