# Generated by Django 2.2.4 on 2019-09-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_proxy', '0004_auto_20190826_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipproxy',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
