# Generated by Django 2.2.4 on 2019-09-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_proxy', '0005_ipproxy_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipproxy',
            name='priority',
            field=models.IntegerField(default=2),
        ),
    ]
